{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multidplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multidplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multidplyr/multidplyr_{{ version }}.tar.gz
  sha256: 8b9aa4c3c3515c31093436453e531eb15d5ef8e0345e83cbbddbd066884d3d20

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-callr >=3.5.1
    - r-crayon
    - r-dplyr >=1.0.0
    - r-magrittr
    - r-qs >=0.18.3
    - r-rlang
    - r-tibble
    - r-vctrs >=0.3.6
  run:
    - r-base
    - r-r6
    - r-callr >=3.5.1
    - r-crayon
    - r-dplyr >=1.0.0
    - r-magrittr
    - r-qs >=0.18.3
    - r-rlang
    - r-tibble
    - r-vctrs >=0.3.6

test:
  commands:
    - $R -e "library('multidplyr')"           # [not win]
    - "\"%R%\" -e \"library('multidplyr')\""  # [win]

about:
  home: https://github.com/tidyverse/multidplyr
  license: MIT
  summary: Partition a data frame across multiple worker processes to provide simple multicore parallelism.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
