{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multidplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multidplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multidplyr/multidplyr_{{ version }}.tar.gz
  sha256: 92b75ed45e39d0525357e916d7a96e44cd943494670267621f8ea3173411d4a3

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-callr >=3.5.1
    - r-cli
    - r-crayon
    - r-dplyr >=1.0.0
    - r-magrittr
    - r-qs >=0.24.1
    - r-rlang >=1.0.6
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.3.6
  run:
    - r-base
    - r-r6
    - r-callr >=3.5.1
    - r-cli
    - r-crayon
    - r-dplyr >=1.0.0
    - r-magrittr
    - r-qs >=0.24.1
    - r-rlang >=1.0.6
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.3.6

test:
  commands:
    - $R -e "library('multidplyr')"           # [not win]
    - "\"%R%\" -e \"library('multidplyr')\""  # [win]

about:
  home: https://github.com/tidyverse/multidplyr
  license: MIT
  summary: Partition a data frame across multiple worker processes to provide simple multicore parallelism.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
